spring:
  application:
    name: avro-consumer
  devtools:
    livereload:
      enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/odenktools
    username: debezium
    password: test1234
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    topic:
      dbserver1: public.api_key

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.odenktools.spring.kafka: DEBUG

server:
  port: 8090
  jetty:
    acceptors: 4
